version: "3"

services:

  postgis:
    image: mdillon/postgis:9.6
    ports:
      - 5432:5432

  datamodel:
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    volumes:
      - ..:/src
